# Generated by Django 4.2.3 on 2024-03-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_deductionallocation_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
