# Generated by Django 4.2.3 on 2024-03-09 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee/profile')),
                ('position', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FullTimeEmployee',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.employee')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medical_leave', models.IntegerField()),
                ('annual_leave', models.IntegerField()),
            ],
            bases=('employee.employee',),
        ),
        migrations.CreateModel(
            name='PartTimeEmployee',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.employee')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            bases=('employee.employee',),
        ),
    ]
